spring:
  redis:
    password: 123456
    host: 192.168.0.101
    port: 6379
    shiro:
      password: 123456
      host: 192.168.0.101
      port: 6379
      timeout: 0
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/weather?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    shiro:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/weather?characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    content-type: text/html=
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  mapper-locations: classpath:config/mapper/*Mapper.xml
  type-aliases-package: com.earthchen.spring.cloud.weather.mapper

server:
  tomcat:
    uri-encoding: utf-8
  port: 8081



