spring:
  redis:
    password: 123456
    host: 192.168.0.101
    port: 6379


  thymeleaf:
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html


server:
  tomcat:
    uri-encoding: utf-8



