package com.earthchen.spring.cloud.weather.vo2;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table city
 */
public class City {
    /**
     * Database Column Remarks:
     *   城市Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cityid
     *
     * @mbg.generated
     */
    private Integer cityid;

    /**
     * Database Column Remarks:
     *   城市名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cityname
     *
     * @mbg.generated
     */
    private String cityname;

    /**
     * Database Column Remarks:
     *   城市拼音
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.citycode
     *
     * @mbg.generated
     */
    private String citycode;

    /**
     * Database Column Remarks:
     *   所属市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.id
     *
     * @return the value of city.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.id
     *
     * @param id the value for city.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cityid
     *
     * @return the value of city.cityid
     *
     * @mbg.generated
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cityid
     *
     * @param cityid the value for city.cityid
     *
     * @mbg.generated
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cityname
     *
     * @return the value of city.cityname
     *
     * @mbg.generated
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cityname
     *
     * @param cityname the value for city.cityname
     *
     * @mbg.generated
     */
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.citycode
     *
     * @return the value of city.citycode
     *
     * @mbg.generated
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.citycode
     *
     * @param citycode the value for city.citycode
     *
     * @mbg.generated
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.province
     *
     * @return the value of city.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.province
     *
     * @param province the value for city.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }
}