package com.earthchen.spring.cloud.weather.vo2;

import lombok.Data;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table city
 */
public class City implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cityid
     *
     * @mbg.generated
     */
    public Integer cityid;

    /**
     * Database Column Remarks:
     *   ��������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cityname
     *
     * @mbg.generated
     */
    public String cityname;

    public String county;

    public String getCounty() {
        return county;
    }

    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * Database Column Remarks:
     *   ����ƴ��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.citycode
     *
     * @mbg.generated
     */
    public String citycode;

    /**
     * Database Column Remarks:
     *   ������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.province
     *
     * @mbg.generated
     */
    public String province;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cityid
     *
     * @return the value of city.cityid
     *
     * @mbg.generated
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cityid
     *
     * @param cityid the value for city.cityid
     *
     * @mbg.generated
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cityname
     *
     * @return the value of city.cityname
     *
     * @mbg.generated
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cityname
     *
     * @param cityname the value for city.cityname
     *
     * @mbg.generated
     */
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.citycode
     *
     * @return the value of city.citycode
     *
     * @mbg.generated
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.citycode
     *
     * @param citycode the value for city.citycode
     *
     * @mbg.generated
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.province
     *
     * @return the value of city.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.province
     *
     * @param province the value for city.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }
}
