package com.earthchen.spring.cloud.weather.vo2;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table forecast
 */
public class Forecast {
    /**
     * Database Column Remarks:
     *   Ԥ��id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast.id
     *
     * @mbg.generated
     */
    public Integer id;

    /**
     * Database Column Remarks:
     *   ��Ӧ�ĳ�����Ϣ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast.cityid
     *
     * @mbg.generated
     */
    public Integer cityid;

    /**
     * Database Column Remarks:
     *   ʱ��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast.date
     *
     * @mbg.generated
     */
    public String date;

    /**
     * Database Column Remarks:
     *   ����¶�
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast.high
     *
     * @mbg.generated
     */
    public Integer high;

    /**
     * Database Column Remarks:
     *   ����¶�
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast.low
     *
     * @mbg.generated
     */
    public Integer low;

    /**
     * Database Column Remarks:
     *   �����ȼ�
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast.fengli
     *
     * @mbg.generated
     */
    public Integer fengli;

    /**
     * Database Column Remarks:
     *   ����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast.fengxiang
     *
     * @mbg.generated
     */
    public String fengxiang;

    /**
     * Database Column Remarks:
     *   ��������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast.type
     *
     * @mbg.generated
     */
    public String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast.id
     *
     * @return the value of forecast.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast.id
     *
     * @param id the value for forecast.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast.cityid
     *
     * @return the value of forecast.cityid
     *
     * @mbg.generated
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast.cityid
     *
     * @param cityid the value for forecast.cityid
     *
     * @mbg.generated
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast.date
     *
     * @return the value of forecast.date
     *
     * @mbg.generated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast.date
     *
     * @param date the value for forecast.date
     *
     * @mbg.generated
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast.high
     *
     * @return the value of forecast.high
     *
     * @mbg.generated
     */
    public Integer getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast.high
     *
     * @param high the value for forecast.high
     *
     * @mbg.generated
     */
    public void setHigh(Integer high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast.low
     *
     * @return the value of forecast.low
     *
     * @mbg.generated
     */
    public Integer getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast.low
     *
     * @param low the value for forecast.low
     *
     * @mbg.generated
     */
    public void setLow(Integer low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast.fengli
     *
     * @return the value of forecast.fengli
     *
     * @mbg.generated
     */
    public Integer getFengli() {
        return fengli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast.fengli
     *
     * @param fengli the value for forecast.fengli
     *
     * @mbg.generated
     */
    public void setFengli(Integer fengli) {
        this.fengli = fengli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast.fengxiang
     *
     * @return the value of forecast.fengxiang
     *
     * @mbg.generated
     */
    public String getFengxiang() {
        return fengxiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast.fengxiang
     *
     * @param fengxiang the value for forecast.fengxiang
     *
     * @mbg.generated
     */
    public void setFengxiang(String fengxiang) {
        this.fengxiang = fengxiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast.type
     *
     * @return the value of forecast.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast.type
     *
     * @param type the value for forecast.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }
}
