package com.earthchen.spring.cloud.weather.vo2;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table message
 */
public class Message {
    /**
     * Database Column Remarks:
     *   消息id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messageId
     *
     * @mbg.generated
     */
    public Long messageid;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.uid
     *
     * @mbg.generated
     */
    public Long uid;

    /**
     * Database Column Remarks:
     *   用户类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.userType
     *
     * @mbg.generated
     */
    public String usertype;

    /**
     * Database Column Remarks:
     *   消息类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messageType
     *
     * @mbg.generated
     */
    public String messagetype;

    /**
     * Database Column Remarks:
     *   转发主贴消息id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.forwardMessageId
     *
     * @mbg.generated
     */
    public String forwardmessageid;

    /**
     * Database Column Remarks:
     *   真实转发id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.realForwardId
     *
     * @mbg.generated
     */
    public Long realforwardid;

    /**
     * Database Column Remarks:
     *   第三方消息id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.thirdMessageId
     *
     * @mbg.generated
     */
    public String thirdmessageid;

    /**
     * Database Column Remarks:
     *   来源应用id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.appId
     *
     * @mbg.generated
     */
    public Long appid;

    /**
     * Database Column Remarks:
     *   json数据
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.jdata
     *
     * @mbg.generated
     */
    public String jdata;

    /**
     * Database Column Remarks:
     *   消息是否屏蔽
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.blockd
     *
     * @mbg.generated
     */
    public Boolean blockd;

    /**
     * Database Column Remarks:
     *   帖子删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.isDelete
     *
     * @mbg.generated
     */
    public Byte isdelete;

    /**
     * Database Column Remarks:
     *   发送设备
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.device
     *
     * @mbg.generated
     */
    public String device;

    /**
     * Database Column Remarks:
     *   ip地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.ipAddress
     *
     * @mbg.generated
     */
    public String ipaddress;

    /**
     * Database Column Remarks:
     *   转发数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.forwardCount
     *
     * @mbg.generated
     */
    public Integer forwardcount;

    /**
     * Database Column Remarks:
     *   评论数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.commentCount
     *
     * @mbg.generated
     */
    public Integer commentcount;

    /**
     * Database Column Remarks:
     *   阅读数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.readCount
     *
     * @mbg.generated
     */
    public Integer readcount;

    /**
     * Database Column Remarks:
     *   点赞数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.praiseCount
     *
     * @mbg.generated
     */
    public Integer praisecount;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.createTime
     *
     * @mbg.generated
     */
    public Date createtime;

    /**
     * Database Column Remarks:
     *   最后更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.updateTime
     *
     * @mbg.generated
     */
    public Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messageId
     *
     * @return the value of message.messageId
     *
     * @mbg.generated
     */
    public Long getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messageId
     *
     * @param messageid the value for message.messageId
     *
     * @mbg.generated
     */
    public void setMessageid(Long messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.uid
     *
     * @return the value of message.uid
     *
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.uid
     *
     * @param uid the value for message.uid
     *
     * @mbg.generated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.userType
     *
     * @return the value of message.userType
     *
     * @mbg.generated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.userType
     *
     * @param usertype the value for message.userType
     *
     * @mbg.generated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messageType
     *
     * @return the value of message.messageType
     *
     * @mbg.generated
     */
    public String getMessagetype() {
        return messagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messageType
     *
     * @param messagetype the value for message.messageType
     *
     * @mbg.generated
     */
    public void setMessagetype(String messagetype) {
        this.messagetype = messagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.forwardMessageId
     *
     * @return the value of message.forwardMessageId
     *
     * @mbg.generated
     */
    public String getForwardmessageid() {
        return forwardmessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.forwardMessageId
     *
     * @param forwardmessageid the value for message.forwardMessageId
     *
     * @mbg.generated
     */
    public void setForwardmessageid(String forwardmessageid) {
        this.forwardmessageid = forwardmessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.realForwardId
     *
     * @return the value of message.realForwardId
     *
     * @mbg.generated
     */
    public Long getRealforwardid() {
        return realforwardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.realForwardId
     *
     * @param realforwardid the value for message.realForwardId
     *
     * @mbg.generated
     */
    public void setRealforwardid(Long realforwardid) {
        this.realforwardid = realforwardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.thirdMessageId
     *
     * @return the value of message.thirdMessageId
     *
     * @mbg.generated
     */
    public String getThirdmessageid() {
        return thirdmessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.thirdMessageId
     *
     * @param thirdmessageid the value for message.thirdMessageId
     *
     * @mbg.generated
     */
    public void setThirdmessageid(String thirdmessageid) {
        this.thirdmessageid = thirdmessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.appId
     *
     * @return the value of message.appId
     *
     * @mbg.generated
     */
    public Long getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.appId
     *
     * @param appid the value for message.appId
     *
     * @mbg.generated
     */
    public void setAppid(Long appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.jdata
     *
     * @return the value of message.jdata
     *
     * @mbg.generated
     */
    public String getJdata() {
        return jdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.jdata
     *
     * @param jdata the value for message.jdata
     *
     * @mbg.generated
     */
    public void setJdata(String jdata) {
        this.jdata = jdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.blockd
     *
     * @return the value of message.blockd
     *
     * @mbg.generated
     */
    public Boolean getBlockd() {
        return blockd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.blockd
     *
     * @param blockd the value for message.blockd
     *
     * @mbg.generated
     */
    public void setBlockd(Boolean blockd) {
        this.blockd = blockd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.isDelete
     *
     * @return the value of message.isDelete
     *
     * @mbg.generated
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.isDelete
     *
     * @param isdelete the value for message.isDelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.device
     *
     * @return the value of message.device
     *
     * @mbg.generated
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.device
     *
     * @param device the value for message.device
     *
     * @mbg.generated
     */
    public void setDevice(String device) {
        this.device = device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.ipAddress
     *
     * @return the value of message.ipAddress
     *
     * @mbg.generated
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.ipAddress
     *
     * @param ipaddress the value for message.ipAddress
     *
     * @mbg.generated
     */
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.forwardCount
     *
     * @return the value of message.forwardCount
     *
     * @mbg.generated
     */
    public Integer getForwardcount() {
        return forwardcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.forwardCount
     *
     * @param forwardcount the value for message.forwardCount
     *
     * @mbg.generated
     */
    public void setForwardcount(Integer forwardcount) {
        this.forwardcount = forwardcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.commentCount
     *
     * @return the value of message.commentCount
     *
     * @mbg.generated
     */
    public Integer getCommentcount() {
        return commentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.commentCount
     *
     * @param commentcount the value for message.commentCount
     *
     * @mbg.generated
     */
    public void setCommentcount(Integer commentcount) {
        this.commentcount = commentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.readCount
     *
     * @return the value of message.readCount
     *
     * @mbg.generated
     */
    public Integer getReadcount() {
        return readcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.readCount
     *
     * @param readcount the value for message.readCount
     *
     * @mbg.generated
     */
    public void setReadcount(Integer readcount) {
        this.readcount = readcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.praiseCount
     *
     * @return the value of message.praiseCount
     *
     * @mbg.generated
     */
    public Integer getPraisecount() {
        return praisecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.praiseCount
     *
     * @param praisecount the value for message.praiseCount
     *
     * @mbg.generated
     */
    public void setPraisecount(Integer praisecount) {
        this.praisecount = praisecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.createTime
     *
     * @return the value of message.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.createTime
     *
     * @param createtime the value for message.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.updateTime
     *
     * @return the value of message.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.updateTime
     *
     * @param updatetime the value for message.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}
