package com.earthchen.spring.cloud.weather.vo2;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_role
 */
public class UserRole {
    /**
     * Database Column Remarks:
     *   userId
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     * Database Column Remarks:
     *   用户角色
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.role
     *
     * @mbg.generated
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   只读字段，创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * Database Column Remarks:
     *   操作人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.createrId
     *
     * @mbg.generated
     */
    private Long createrid;

    /**
     * Database Column Remarks:
     *   操作IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.createrIp
     *
     * @mbg.generated
     */
    private String createrip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.jdata
     *
     * @mbg.generated
     */
    private String jdata;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.uid
     *
     * @return the value of user_role.uid
     *
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.uid
     *
     * @param uid the value for user_role.uid
     *
     * @mbg.generated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.role
     *
     * @return the value of user_role.role
     *
     * @mbg.generated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.role
     *
     * @param role the value for user_role.role
     *
     * @mbg.generated
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.id
     *
     * @return the value of user_role.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.id
     *
     * @param id the value for user_role.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.createTime
     *
     * @return the value of user_role.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.createTime
     *
     * @param createtime the value for user_role.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.createrId
     *
     * @return the value of user_role.createrId
     *
     * @mbg.generated
     */
    public Long getCreaterid() {
        return createrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.createrId
     *
     * @param createrid the value for user_role.createrId
     *
     * @mbg.generated
     */
    public void setCreaterid(Long createrid) {
        this.createrid = createrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.createrIp
     *
     * @return the value of user_role.createrIp
     *
     * @mbg.generated
     */
    public String getCreaterip() {
        return createrip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.createrIp
     *
     * @param createrip the value for user_role.createrIp
     *
     * @mbg.generated
     */
    public void setCreaterip(String createrip) {
        this.createrip = createrip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.jdata
     *
     * @return the value of user_role.jdata
     *
     * @mbg.generated
     */
    public String getJdata() {
        return jdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.jdata
     *
     * @param jdata the value for user_role.jdata
     *
     * @mbg.generated
     */
    public void setJdata(String jdata) {
        this.jdata = jdata;
    }
}