package com.earthchen.spring.cloud.weather.vo2;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table weather
 */
public class Weather {
    /**
     * Database Column Remarks:
     *   当天天气id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.id
     *
     * @mbg.generated
     */
    public Integer id;

    /**
     * Database Column Remarks:
     *   对应城市信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.cityid
     *
     * @mbg.generated
     */
    public Integer cityid;

    /**
     * Database Column Remarks:
     *   预防感冒小提示
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.ganmao
     *
     * @mbg.generated
     */
    public String ganmao;

    /**
     * Database Column Remarks:
     *   当天天气温度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.wendu
     *
     * @mbg.generated
     */
    public Integer wendu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.id
     *
     * @return the value of weather.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.id
     *
     * @param id the value for weather.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.cityid
     *
     * @return the value of weather.cityid
     *
     * @mbg.generated
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.cityid
     *
     * @param cityid the value for weather.cityid
     *
     * @mbg.generated
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.ganmao
     *
     * @return the value of weather.ganmao
     *
     * @mbg.generated
     */
    public String getGanmao() {
        return ganmao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.ganmao
     *
     * @param ganmao the value for weather.ganmao
     *
     * @mbg.generated
     */
    public void setGanmao(String ganmao) {
        this.ganmao = ganmao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.wendu
     *
     * @return the value of weather.wendu
     *
     * @mbg.generated
     */
    public Integer getWendu() {
        return wendu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.wendu
     *
     * @param wendu the value for weather.wendu
     *
     * @mbg.generated
     */
    public void setWendu(Integer wendu) {
        this.wendu = wendu;
    }
}